### ISSUE TITLE
Mistake in Readme.md

### ISSUE THREAD

**Issue by binarykitchen** [teawithfruit/node-singleton-event#3]
Shouldn't it be like this?

``` js
var singletonEvent = require('node-singleton-event');
singletonEvent.emit('talk', 'hello world');
```

otherwise you'll get a `Error: Cannot find module 'singleton-event'`

**Comment by teawithfruit** [comment]
That's right. Issue is solved with the following commit. db1c53fb2832214619af4feade79ba8ae0cc74d7
