### ISSUE TITLE
__proto__ is not supported in IE10

### ISSUE THREAD

**Issue by binarykitchen** [teawithfruit/node-singleton-event#5]
When I browserify my app along with your package and test the app on IE10, I get this error

```
TypeError: Object doesn't support property or method 'on' 
```

After some debugging and research I found out that this code line https://github.com/teawithfruit/node-singleton-event/blob/master/index.js#L15 does not get on well with IE10, unfortunately.

Other sources confirm this, for example http://smalljs.org/object/events/event-emitter/

Maybe try using `util.inherits()` or mixins instead?

**Comment by binarykitchen** [comment]
I need this to be fixed asap ... going to fork and npm publish under a new name - sorry

**Comment by binarykitchen** [comment]
Here it is https://github.com/binarykitchen/despot ... original credits go to you. If you have any objections, let me know. Cheers

**Comment by teawithfruit** [comment]
Sorry for being late. I've updated the code right now.

**Comment by binarykitchen** [comment]
@teawithfruit well, too late, i already published a similar package, https://github.com/binarykitchen/despot

it's an important part for my videomail.io app and i cannot risk it, to wait so long until changes are made. but i know, having two similar npm packages is no good. what shall we do?

three suggestions
a) make me a contributor of node-singleton-event and i ll remove my other package
b) the other way around, i ll make you a contributor of my package and we remove node-singleton-event
c) we keep both packages and see how it goes

hope you understand and we can keep the npm ecosystem clean
